In [11]:
#-*- coding: utf-8 -*-
import warnings
warnings.filterwarnings('ignore')
import csv
import pandas as pd
graph = pd.read_csv("C:/Users/한유린/Desktop/객체지향 프로그래밍/오존_월별_도시별_대기오염도_2010.csv",encoding='euc-kr', engine='python')
graph

,시도별,2010. 01,2010. 02,2010. 03,2010. 04,2010. 05,2010. 06,2010. 07,2010. 08,2010. 09,2010. 10,2010. 11,2010. 12
0,서울,0.011,0.016,0.024,0.026,0.030,0.033,0.023,0.018,0.015,0.014,0.013,0.010
1,부산,0.021,0.024,0.031,0.033,0.036,0.035,0.022,0.020,0.024,0.029,0.020,0.018
2,대구,0.014,0.018,0.025,0.030,0.034,0.039,0.022,0.022,0.018,0.016,0.013,0.013
3,인천,0.014,0.018,0.025,0.027,0.029,0.032,0.021,0.019,0.018,0.018,0.016,0.013
4,광주,0.017,0.019,0.026,0.031,0.039,0.037,0.024,0.022,0.022,0.022,0.015,0.016
5,대전,0.011,0.015,0.023,0.027,0.037,0.037,0.024,0.022,0.018,0.016,0.015,0.012
6,울산,0.018,0.021,0.026,0.028,0.032,0.028,0.020,0.021,0.022,0.025,0.017,0.017
7,경기,0.011,0.015,0.023,0.026,0.033,0.034,0.024,0.019,0.017,0.016,0.014,0.011
8,강원,0.018,0.021,0.029,0.035,0.042,0.036,0.024,0.020,0.018,0.018,0.018,0.017
9,충북,0.012,0.016,0.026,0.030,0.039,0.037,0.023,0.021,0.018,0.015,0.013,0.011
10,충남,0.018,0.022,0.029,0.033,0.040,0.038,0.025,0.020,0.019,0.021,0.020,0.016
11,전북,0.016,0.020,0.025,0.028,0.031,0.033,0.021,0.019,0.021,0.022,0.019,0.017
12,전남,0.023,0.024,0.029,0.034,0.040,0.037,0.021,0.020,0.024,0.031,0.023,0.021
13,경북,0.019,0.022,0.029,0.035,0.038,0.038,0.022,0.020,0.018,0.018,0.018,0.017
14,경남,0.018,0.021,0.028,0.032,0.037,0.037,0.023,0.023,0.023,0.025,0.017,0.016
15,제주,0.036,0.040,0.046,0.049,0.044,0.041,0.031,0.025,0.035,0.045,0.037,0.030

In [21]:
graph[['2010. 01','2010. 02','2010. 03','2010. 04','2010. 05','2010. 06','2010. 07','2010. 08','2010. 09','2010. 10','2010. 11','2010. 12']] = graph[['2010. 01','2010. 02','2010. 03','2010. 04','2010. 05','2010. 06','2010. 07','2010. 08','2010. 09','2010. 10','2010. 11','2010. 12']].astype(float)

In [23]:
graph.dtypes

시도별          object
2010. 01    float64
2010. 02    float64
2010. 03    float64
2010. 04    float64
2010. 05    float64
2010. 06    float64
2010. 07    float64
2010. 08    float64
2010. 09    float64
2010. 10    float64
2010. 11    float64
2010. 12    float64
dtype: object

In [40]:
graph['총평균'] = graph.mean(axis=1)
graph = graph.drop(["평균"],axis = 1)
graph

,시도별,2010. 01,2010. 02,2010. 03,2010. 04,2010. 05,2010. 06,2010. 07,2010. 08,2010. 09,2010. 10,2010. 11,2010. 12,총평균
0,서울,0.011,0.016,0.024,0.026,0.030,0.033,0.023,0.018,0.015,0.014,0.013,0.010,0.019417
1,부산,0.021,0.024,0.031,0.033,0.036,0.035,0.022,0.020,0.024,0.029,0.020,0.018,0.026083
2,대구,0.014,0.018,0.025,0.030,0.034,0.039,0.022,0.022,0.018,0.016,0.013,0.013,0.022000
3,인천,0.014,0.018,0.025,0.027,0.029,0.032,0.021,0.019,0.018,0.018,0.016,0.013,0.020833
4,광주,0.017,0.019,0.026,0.031,0.039,0.037,0.024,0.022,0.022,0.022,0.015,0.016,0.024167
5,대전,0.011,0.015,0.023,0.027,0.037,0.037,0.024,0.022,0.018,0.016,0.015,0.012,0.021417
6,울산,0.018,0.021,0.026,0.028,0.032,0.028,0.020,0.021,0.022,0.025,0.017,0.017,0.022917
7,경기,0.011,0.015,0.023,0.026,0.033,0.034,0.024,0.019,0.017,0.016,0.014,0.011,0.020250
8,강원,0.018,0.021,0.029,0.035,0.042,0.036,0.024,0.020,0.018,0.018,0.018,0.017,0.024667
9,충북,0.012,0.016,0.026,0.030,0.039,0.037,0.023,0.021,0.018,0.015,0.013,0.011,0.021750
10,충남,0.018,0.022,0.029,0.033,0.040,0.038,0.025,0.020,0.019,0.021,0.020,0.016,0.025083
11,전북,0.016,0.020,0.025,0.028,0.031,0.033,0.021,0.019,0.021,0.022,0.019,0.017,0.022667
12,전남,0.023,0.024,0.029,0.034,0.040,0.037,0.021,0.020,0.024,0.031,0.023,0.021,0.027250
13,경북,0.019,0.022,0.029,0.035,0.038,0.038,0.022,0.020,0.018,0.018,0.018,0.017,0.024500
14,경남,0.018,0.021,0.028,0.032,0.037,0.037,0.023,0.023,0.023,0.025,0.017,0.016,0.025000
15,제주,0.036,0.040,0.046,0.049,0.044,0.041,0.031,0.025,0.035,0.045,0.037,0.030,0.038250

In [42]:
def get_status(s):
    if s < 0.031:
        status = "좋음"
    elif s < 0.091:
        status = "보통"
    elif s < 0.151:
        status = "나쁨"
    else:
        status = "아주 나쁨"
    return status

In [43]:
graph["상태"] = graph["총평균"].apply(lambda s: get_status(s))
graph

,시도별,2010. 01,2010. 02,2010. 03,2010. 04,2010. 05,2010. 06,2010. 07,2010. 08,2010. 09,2010. 10,2010. 11,2010. 12,총평균,상태
0,서울,0.011,0.016,0.024,0.026,0.030,0.033,0.023,0.018,0.015,0.014,0.013,0.010,0.019417,좋음
1,부산,0.021,0.024,0.031,0.033,0.036,0.035,0.022,0.020,0.024,0.029,0.020,0.018,0.026083,좋음
2,대구,0.014,0.018,0.025,0.030,0.034,0.039,0.022,0.022,0.018,0.016,0.013,0.013,0.022000,좋음
3,인천,0.014,0.018,0.025,0.027,0.029,0.032,0.021,0.019,0.018,0.018,0.016,0.013,0.020833,좋음
4,광주,0.017,0.019,0.026,0.031,0.039,0.037,0.024,0.022,0.022,0.022,0.015,0.016,0.024167,좋음
5,대전,0.011,0.015,0.023,0.027,0.037,0.037,0.024,0.022,0.018,0.016,0.015,0.012,0.021417,좋음
6,울산,0.018,0.021,0.026,0.028,0.032,0.028,0.020,0.021,0.022,0.025,0.017,0.017,0.022917,좋음
7,경기,0.011,0.015,0.023,0.026,0.033,0.034,0.024,0.019,0.017,0.016,0.014,0.011,0.020250,좋음
8,강원,0.018,0.021,0.029,0.035,0.042,0.036,0.024,0.020,0.018,0.018,0.018,0.017,0.024667,좋음
9,충북,0.012,0.016,0.026,0.030,0.039,0.037,0.023,0.021,0.018,0.015,0.013,0.011,0.021750,좋음
10,충남,0.018,0.022,0.029,0.033,0.040,0.038,0.025,0.020,0.019,0.021,0.020,0.016,0.025083,좋음
11,전북,0.016,0.020,0.025,0.028,0.031,0.033,0.021,0.019,0.021,0.022,0.019,0.017,0.022667,좋음
12,전남,0.023,0.024,0.029,0.034,0.040,0.037,0.021,0.020,0.024,0.031,0.023,0.021,0.027250,좋음
13,경북,0.019,0.022,0.029,0.035,0.038,0.038,0.022,0.020,0.018,0.018,0.018,0.017,0.024500,좋음
14,경남,0.018,0.021,0.028,0.032,0.037,0.037,0.023,0.023,0.023,0.025,0.017,0.016,0.025000,좋음
15,제주,0.036,0.040,0.046,0.049,0.044,0.041,0.031,0.025,0.035,0.045,0.037,0.030,0.038250,보통

In [46]:
graph1 = graph[["시도별","총평균","상태"]]
graph1

   시도별       총평균  상태
0   서울  0.019417  좋음
1   부산  0.026083  좋음
2   대구  0.022000  좋음
3   인천  0.020833  좋음
4   광주  0.024167  좋음
5   대전  0.021417  좋음
6   울산  0.022917  좋음
7   경기  0.020250  좋음
8   강원  0.024667  좋음
9   충북  0.021750  좋음
10  충남  0.025083  좋음
11  전북  0.022667  좋음
12  전남  0.027250  좋음
13  경북  0.024500  좋음
14  경남  0.025000  좋음
15  제주  0.038250  보통