In [7]:
import csv
import pandas as pd

def get_status(s):
    if s < 0.031:
        status = "좋음"
    elif s < 0.091:
        status = "보통"
    elif s < 0.151:
        status = "나쁨"
    else:
        status = "아주 나쁨"
    return status
    
graph = pd.read_csv("C:/Users/TeamProject/오존_월별_도시별_대기오염도_2013.csv",encoding='euc-kr', engine='python')
graph["총평균"] = graph.mean(axis=1)
graph["상태"] = graph["총평균"].apply(lambda s: get_status(s))
graph_2013 = graph[["시도별","총평균","상태"]]
graph_2013

   시도별       총평균  상태
0   서울  0.021917  좋음
1   부산  0.028750  좋음
2   대구  0.025250  좋음
3   인천  0.024917  좋음
4   광주  0.029083  좋음
5   대전  0.024250  좋음
6   울산  0.028083  좋음
7   경기  0.023417  좋음
8   강원  0.026417  좋음
9   충북  0.026000  좋음
10  충남  0.028500  좋음
11  전북  0.028167  좋음
12  전남  0.031917  보통
13  경북  0.028167  좋음
14  경남  0.030417  좋음
15  제주  0.033833  보통

In [3]:
graph = pd.read_csv("C:/Users/TeamProject/오존_월별_도시별_대기오염도_2014.csv",encoding='euc-kr', engine='python')
graph["총평균"] = graph.mean(axis=1)
graph["상태"] = graph["총평균"].apply(lambda s: get_status(s))
graph_2014 = graph[["시도별","총평균","상태"]]
graph_2014

   시도별       총평균  상태
0   서울  0.023167  좋음
1   부산  0.029250  좋음
2   대구  0.026083  좋음
3   인천  0.025833  좋음
4   광주  0.028417  좋음
5   대전  0.025833  좋음
6   울산  0.027750  좋음
7   경기  0.024667  좋음
8   강원  0.028250  좋음
9   충북  0.026167  좋음
10  충남  0.028583  좋음
11  전북  0.030167  좋음
12  전남  0.031000  보통
13  경북  0.028750  좋음
14  경남  0.029750  좋음
15  제주  0.037333  보통

In [4]:
graph = pd.read_csv("C:/Users/TeamProject/오존_월별_도시별_대기오염도_2015.csv",encoding='euc-kr', engine='python')
graph["총평균"] = graph.mean(axis=1)
graph["상태"] = graph["총평균"].apply(lambda s: get_status(s))
graph_2015 = graph[["시도별","총평균","상태"]]
graph_2015

   시도별       총평균  상태
0   서울  0.022182  좋음
1   부산  0.028636  좋음
2   대구  0.026182  좋음
3   인천  0.024818  좋음
4   광주  0.028273  좋음
5   대전  0.024636  좋음
6   울산  0.027545  좋음
7   경기  0.024545  좋음
8   강원  0.027909  좋음
9   충북  0.025091  좋음
10  충남  0.027818  좋음
11  전북  0.029000  좋음
12  전남  0.029364  좋음
13  경북  0.030364  좋음
14  경남  0.029364  좋음
15  제주  0.036273  보통